# Generated by Django 6.0.7 on 2026-08-17 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='PaidAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='paymentID',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.payment'),
        ),
    ]
